// angular/SampleECommerce/src/app/cart/cart.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { CartQuery } from '../services/cart-state/cart.query';
import { CartService } from '../services/cart.service';
import { CartData } from '../services/models/cart-data';
import { ItemData } from '../services/models/item-data';

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.css']
})
export class CartComponent implements OnInit {

  cartitems$: Observable<CartData[]> | undefined;
  constructor(private cartQuery: CartQuery, private cartService: CartService) { }

  ngOnInit(): void {
    this.cartitems$ = this.cartQuery.selectAll();
  }

  trackByFn(index: number, cartData: CartData) {
    return cartData.id;
  }

  remove(itemData: ItemData){
    this.cartService.remove(itemData);
  }
  
}

<ng-container *ngIf="cartitems$ | async as cartitems; else empty">
    <ng-container *ngIf="cartitems && cartitems.length > 0; else empty">
        <table class="table">
            <thead>
                <tr>
                    <th>Category</th>
                    <th>Item</th>
                    <th>Snapshot</th>
                    <th>Count</th>
                    <th>Remove</th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let cartData of cartitems trackBy: trackByFn">
                    <td style="text-align: center;">{{cartData.itemData.category}}</td>
                    <td style="text-align: center;">{{cartData.itemData.imageTitle}}</td>
                    <td style="text-align: center;"><img height="50" width="50" [src]="cartData.itemData.imageUrl" /></td>
                    <td style="text-align: center;">{{cartData.count}}</td>
                    <td style="text-align: center;">
                        <button mat-fab color="accent" (click)="remove(cartData.itemData)">
                            <mat-icon>delete</mat-icon>
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
        <div style="display:flex;flex-direction:row-reverse;">
            <button mat-raised-button color="accent" style="margin-right:10px;">Check Out</button>
        </div>
    </ng-container>
</ng-container>
<ng-template #empty>No Items in Cart.</ng-template>

// react/sample-ecommerce/src/components/Cart/Cart.tsx
import { Button, IconButton } from '@material-ui/core';
import { Delete } from '@material-ui/icons';
import React from 'react';
import { useDispatch } from 'react-redux';
import { ItemData } from '../../models/itemData';
import { remove, useCartSelector } from '../../services/cartSlice';
import './Cart.css';

const Cart: React.FC = () => {
  const cartData = useCartSelector((state) => state.cartReducer.cartData);
  const dispatch = useDispatch();
  const removeFromCart = (itemData: ItemData) => {
    dispatch(remove(itemData))
  }

  return (
    <div>
      {
        cartData ? cartData.length > 0 ?
          <>
            <table className="table">
              <thead>
                <tr>
                  <th>Category</th>
                  <th>Item</th>
                  <th>Snapshot</th>
                  <th>Count</th>
                  <th>Remove</th>
                </tr>
              </thead>
              <tbody></tbody>
              {
                cartData?.map((cartItem) => {
                  return (
                    <tr key={cartItem.id}>
                      <td>{cartItem.itemData.category}</td>
                      <td>{cartItem.itemData.imageTitle}</td>
                      <td><img height="50" width="50" src={cartItem.itemData.imageUrl} /></td>
                      <td>{cartItem.count}</td>
                      <td>
                        <IconButton onClick={() => removeFromCart(cartItem.itemData)}>
                          <Delete />
                        </IconButton>
                      </td>
                    </tr>
                  )
                })
              }
            </table>
            <div className="align-right">
              <Button variant="contained" color="primary" className="margin-right-10">
                Check Out
              </Button>
            </div>
          </>
          : <span>No Items in Cart.</span> : <span>No Items in Cart.</span>
      }
    </div>
  )
}

export default Cart;
